### ISSUE TITLE
[Feature] - Customer Onboarding Showcase for DigiWF and Miranum Demos

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#10]
- [x] Description created
- [x] Reviewed by peer: <tag-person-here>
- [x] Prioritised

# Description
We want to have a showroom which is suitable for demos and easily adaptable to various customers. 
Therefore, we want to create a customer-onboarding-process. Which uses miranum connect as well as ide. 
Besides, we also want to have the possibility to demo DigiWF with the developed solution

## Sub-Tasks
 
```[tasklist]
### Tasks
- [x] Create Customer Onboarding Process
- [x] Create Forms for the Process
- [x] Create miranum worker
    - [x] Send Mail worker 
    - [x] evaluation worker
- [x] Customer Frontend to trigger processes
- [x] Process starter App 
- [x] Integration with DigiWF
```
