### ISSUE TITLE
[Fix] - Refactor miranum-consulting repo to not be a maven project

### ISSUE THREAD

**Issue by rami-nk** [FlowSquad/miranum-consulting#13]
- [x] Description created
- [ ] Reviewed by peer: @Hafflgav 
- [ ] Prioritised

# Description

The miranum-consulting repo currently is a maven project. I'm not sure why we chose to do that. It restricts us when we want to name two modules in two different showcase projects the same.
What is the advantage of having it as a maven project?

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] <your-issue-here>
- [ ] Change maven-consulting to not be a maven project
- [ ] Remove parent for all submodules
- [ ] rename directories and modules (are named differently at the moment, to have a unique name inside of the maven-project)
- [ ] Check that every example is working
```

**Comment by Hafflgav** [comment]
You are completely right! :) 
I think it would be great to change this! As far as I remember it I added a pom due to some problems when having opened it in IntelliJ. But this should not be a reason for having a parent maven project for every example. 

Thanks! 💯 
Looking forward to the changes!

**Comment by DaAnda97** [comment]
Removing the pom in miranum-consulting resulted in IntelliJ igonring all root files and the forms-flow-showcase, which is not a maven project.
We just should not set miranum-consulting as parent in each showcase. Please see: https://github.com/FlowSquad/miranum-consulting/pull/15
