### ISSUE TITLE
[Feature] - 

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#4]
- [x] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
Migrate[ pizza-e-vino example](https://github.com/Hafflgav/pizza-e-vino) to the pizza-order-showcase. So we can build a complete example in this mono-repo

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Copy the pizza-e-vino project to the pizza-order-showcase
- [ ] Update the package structure
- [ ] Update the readme's 
- [ ] Update the references in the documentation 
```
