### ISSUE TITLE
[Feature] - Update Process Model for Domain Events

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#5]
- [x] Description created
- [ ] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
Change the process model in such a way that Domain Events can be thrown in a meaningful way. 
This can be by adding another little process which is contextually separated or by dealing with intermediate message events. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Brainstorm possible ideas and discuss them 
- [ ] Change the process model and ensure that it still can run 
- [ ] Implement new services if necessary 
```
