### ISSUE TITLE
[Feature] - Unify the Pizza-order-showcase

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#6]
- [x] Description created
- [x] Reviewed by peer: @DaAnda97 
- [ ] Prioritised

# Description
Unify the pizza-order-showcase so it builds on top of the pizza-e-vino example. Make sure they are named equally and that it is clear that the pizza-order-showcase with the clean architecture is just another iteration of the same process. 

## Sub-Tasks
 
```[tasklist]
### Tasks
- [ ] Update all BPMN files accordingly 
- [ ] Improve naming where necessary. 
```
