### ISSUE TITLE
[Feature] - Add Kafka and Domain Events to Pizza-Order-Showcase

### ISSUE THREAD

**Issue by Hafflgav** [FlowSquad/miranum-consulting#7]
- [x] Description created
- [x] Reviewed by peer: @DaAnda97 
- [x] Prioritised

# Description
To demonstrate a loosely coupled architecture which follows the guidelines of domain driven design we want to throw domain events and publish them to Kafka. 

## Sub-Tasks
```[tasklist]
### Tasks
- [x] Setup and configure Kafka. Add it to the Stack
- [x] Add code to throw domain events
```
